# fly.toml app configuration file generated for sitepress on 2023-09-05T09:37:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sitepress"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sjc"
processes = []

[build]

[deploy]
  strategy = "immediate"

[env]
  PORT = "8080"
  SERVER_COMMAND = "bundle exec sitepress server --no-site-reloading --no-site-error-reporting --bind-address 0.0.0.0"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
